# coding: utf-8

"""
    CutMeShort CMS API

    Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from pydantic import ValidationError

from cms_python.models.lead_payload import LeadPayload

class TestLeadPayload(unittest.TestCase):
    """LeadPayload validation tests"""

    def test_valid_mode_and_alias_dump(self):
        payload = LeadPayload(
            click_id="id_123",
            event_name="signup_started",
            customer_external_id="user_42",
            mode="deferred",
        )
        dumped = payload.to_dict()
        self.assertEqual(dumped["mode"], "deferred")
        self.assertEqual(dumped["eventName"], "signup_started")

    def test_invalid_mode_rejected(self):
        with self.assertRaises(ValidationError):
            LeadPayload(
                event_name="signup_started",
                customer_external_id="user_42",
                mode="invalid-mode",
            )

if __name__ == '__main__':
    unittest.main()
