# coding: utf-8

"""
    CutMeShort CMS API

    Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from pydantic import ValidationError

from cms_python.models.sale_payload import SalePayload

class TestSalePayload(unittest.TestCase):
    """SalePayload validation tests"""

    def test_valid_payload(self):
        payload = SalePayload(
            click_id="id_123",
            event_name="purchase_completed",
            customer_external_id="user_123",
            invoice_id="inv_987",
            amount=4999,
            currency="USD",
        )
        dumped = payload.to_dict()
        self.assertEqual(dumped["invoiceId"], "inv_987")
        self.assertEqual(dumped["currency"], "USD")

    def test_currency_length_validation(self):
        with self.assertRaises(ValidationError):
            SalePayload(
                click_id="id_123",
                event_name="purchase_completed",
                customer_external_id="user_123",
                invoice_id="inv_987",
                amount=4999,
                currency="US",
            )

if __name__ == '__main__':
    unittest.main()
