# coding: utf-8

"""
    CutMeShort CMS API

    Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cms_python.models.error_response import ErrorResponse

class TestErrorResponse(unittest.TestCase):
    """ErrorResponse model tests"""

    def test_error_response_roundtrip(self):
        model = ErrorResponse(
            success=False,
            error="Validation failed",
            type="UnprocessableEntityError",
            status_code=422,
            details={"field": "currency"},
        )
        dumped = model.to_dict()
        self.assertEqual(dumped["statusCode"], 422)
        rehydrated = ErrorResponse.from_dict(dumped)
        self.assertEqual(rehydrated.error, "Validation failed")

if __name__ == '__main__':
    unittest.main()
