# coding: utf-8

# flake8: noqa

"""
    CutMeShort CMS API

    Official API for the CutMeShort CMS platform.  This API allows tracking of leads and sales, including deferred lead attribution. In deferred attribution, the first lead call stores the clickId-to-customerExternalId association using `mode: deferred`. Subsequent lead events should be sent as normal events without `mode`, and the backend resolves the stored association automatically. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CMSClient",
    "TrackingApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ErrorResponse",
    "LeadPayload",
    "SalePayload",
    "TrackResponse",
]

# import simplified client
from cms_python.client import CMSClient as CMSClient

# import apis into sdk package
from cms_python.api.tracking_api import TrackingApi as TrackingApi

# import ApiClient
from cms_python.api_response import ApiResponse as ApiResponse
from cms_python.api_client import ApiClient as ApiClient
from cms_python.configuration import Configuration as Configuration
from cms_python.exceptions import OpenApiException as OpenApiException
from cms_python.exceptions import ApiTypeError as ApiTypeError
from cms_python.exceptions import ApiValueError as ApiValueError
from cms_python.exceptions import ApiKeyError as ApiKeyError
from cms_python.exceptions import ApiAttributeError as ApiAttributeError
from cms_python.exceptions import ApiException as ApiException

# import models into sdk package
from cms_python.models.error_response import ErrorResponse as ErrorResponse
from cms_python.models.lead_payload import LeadPayload as LeadPayload
from cms_python.models.sale_payload import SalePayload as SalePayload
from cms_python.models.track_response import TrackResponse as TrackResponse

